### ISSUE TITLE
Crash on API31+ due to missing BLUETOOTH_CONNECT permission

### ISSUE THREAD

**Issue by msimonides** [DimitriJunker/mtkdownload#2]
Opening preferences causes a crash. It's caused by lack of runtime permission `BLUETOOTH_CONNECT`. The crash occurs when calling `mBluetoothAdapter.getBondedDevices()` in `PrefsFragment`. This makes the app completely unusable on newer devices.

See: https://developer.android.com/guide/topics/connectivity/bluetooth/permissions

**Comment by DimitriJunker** [comment]
Hi,

I solved the Bluetooth problem, but scoped storage is the bigger problem, sorry it will the some more time.
Greetings
Dimitri

Am 14. Mai 2023 20:58:41 MESZ schrieb Marcin Simonides ***@***.***>:

**Comment by msimonides** [comment]
I've been using the app recently on Android 14 with success, so I'll close this issue.
